config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#index'

  # Active admin routing
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Devise Authentification routing
  devise_for :users

  resource :profile, only: [:show, :edit, :update]
  resources :events, only: [:index]
  resources :bookings, only: [:index, :new, :create]

  namespace :host do
    resources :slots, only: [:index, :create]
  end
  namespace :guest do
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :slot

  validates :people, presence: true, numericality: { greater_than: 0 }
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  before_validation :downcase_attributes

  belongs_to :user

  def address
    [street, zipcode, city, country].reject(&:blank?).join(', ')
  end

  def fullname
    [firstname, lastname].reject(&:blank?).map(&:capitalize).join(' ')
  end

  private

  #
  # ensure all profile attributes are downcased
  #
  def downcase_attributes
    attributes.each { |_field, value| value.downcase! if value.is_a? String }
  end
end

app/models/slot.rb
# frozen_string_literal: true

class Slot < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :guests, through: :bookings, source: :user

  validates :status, presence: true
  validates :scheduled_at, presence: true
  validates :daytime, presence: true
  validates :max_people, presence: true, numericality: { greater_than: 0 }

  enum status: { available: 0, booked: 1, payed: 2 }
  enum daytime: { lunch: 0, dinner: 1 }

  scope :bookable_for, ->(user) { available.where.not(user: user).where('scheduled_at > ?', Time.zone.now) }

  def bookable_for?(user)
    Slot.bookable_for(user).exists? id
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :slots, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :events, through: :bookings, source: :slot, inverse_of: 'guest'

  enum identity: { guest: 0, host: 1 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = current_user.bookings.includes(:slot)
  end

  def new
    @booking = current_user.bookings.build booking_params
  end

  def create
    @booking = current_user.bookings.build booking_params
    if @booking.slot.bookable_for?(current_user) && @booking.save
      @booking.slot.booked!
      redirect_to bookings_path, notice: 'Event has been booked.'
    else
      redirect_to events_path, alert: 'Event could not be booked.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:slot_id, :people)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Slot.bookable_for(current_user).includes(:user)
  end
end

app/controllers/guest_controller.rb
# frozen_string_literal: true

class GuestController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_guest!

  private

  def authorize_guest!
    redirect_to root_path, alert: 'You can not access this page.' unless current_user.guest?
  end
end

app/controllers/host/slots_controller.rb
# frozen_string_literal: true

module Host
  class SlotsController < HostController
    def index
      @slots = current_user.slots
    end

    def create
      slot = current_user.slots.build slot_params
      if slot.save
        redirect_to host_slots_path, notice: 'Slot created'
      else
        redirect_to host_slots_path, alert: 'Slot not created'
      end
    end

    private

    def slot_params
      params.require(:slot).permit(:scheduled_at, :daytime, :max_people)
    end
  end
end

app/controllers/host_controller.rb
# frozen_string_literal: true

class HostController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_host!

  private

  def authorize_host!
    redirect_to root_path, alert: 'You can not access this page.' unless current_user.host?
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile || current_user.create_profile
  end

  def edit
    @profile = current_user.profile || current_user.create_profile
  end

  def update
    if current_user.profile&.update profile_params.to_h
      redirect_to profile_path, notice: 'Account information saved..'
    else
      redirect_to profile_path, alert: 'Account information not saved.'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:lastname, :firstname, :street, :city, :zipcode, :country)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role='alert' >
    <%= notice %>
    <button type='button' class='close' data-dismiss='alert' aria-label='close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role='alert' >
    <%= alert %>
    <button type='button' class='close' data-dismiss='alert' aria-label='close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar main-navbar sticky-top navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="#">Chiz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Events', events_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Bookings', bookings_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Account', profile_path, class: 'nav-link' %>
      </li>

      <% if current_user&.host? %>
        <li class="nav-item">
          <%= link_to 'Slots', host_slots_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>

  </div>
</nav>

app/views/bookings/_booking.html.erb
<div class='col-xl-4 col-12'>
  <div class='card'>
    <%= image_tag 'sample.jpg', class: 'card-img-top' %>
    <div class='card-body'>
      <h5 class='card-title'>@Maisons-Laffite for <%= booking.people %> people</h5>
      <h5 class='card-title'><%= booking.slot.scheduled_at&.strftime("%d/%m/%Y") %> for <%= booking.slot.daytime %></h5>
      <h6 class='card-subtitle'>Hosted by : Babar bouba</h6>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'>Booked events</h4>
  </div>
</div>

<div class='row'>
  <%= render @bookings %>
</div>

app/views/bookings/new.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'><%= @booking.slot.daytime %> <%= @booking.slot.scheduled_at&.strftime("%d/%m/%Y") %></h4>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <p>Hosted by <%= @booking.slot.user.email %>, up to <%= @booking.slot.max_people %> people.</p>
  </div>
</div>

<%= form_with model: @booking, local: true do |form| %>
  <%= form.hidden_field :slot_id, value: @booking.slot_id %>
  <div class='row'>
    <div class='col'>
      <div class='form-group'>
        <%= form.label :people %>
        <%= form.select :people, (1..@booking.slot.max_people).map { |int| [int, int]}, class: 'form-control' %>
      </div>
    </div>
  </div>
  <br>
  <div class='row'>
    <div class='col'>
        <%= form.submit 'Confirm booking', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/events/_event.html.erb
<div class='col-xl-4 col-12'>
  <div class='card' id='event-card-<%= event.id %>'>
    <%= image_tag 'sample.jpg', class: 'card-img-top' %>

    <div class='card-body'>
      <h5 class='card-title'>@Maisons-Laffite up to <%= event.max_people %> people</h5>
      <h5 class='card-title'><%= event.scheduled_at&.strftime("%d/%m/%Y") %> for <%= event.daytime %></h5>
      <h6 class='card-subtitle'>Hosted by : <%= event.user.email %></h6>
      <%= link_to 'Book event', new_booking_path(booking: {slot_id: event.id}), class: 'card-link' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'>Available events</h4>
  </div>
</div>

<div class='row'>
  <%= render partial: 'event', collection: @events %>
</div>

app/views/home/index.html.erb
<h1>Guest root page</h1>

app/views/host/slots/_slot.html.erb
<div class='col-xl-4 col-12'>
  <div class='card' id='slot-card-<%= slot.id %>'>
    <%= image_tag 'sample.jpg', class: 'card-img-top' %>
    <div class='card-body'>
      <h5 class='card-title'>@Maisons-Laffite up to <%= slot.max_people %> people</h5>
      <h5 class='card-title'><%= slot.scheduled_at&.strftime("%d/%m/%Y") %> for <%= slot.daytime %></h5>
      <h6 class='card-subtitle'>Slot status : <%= slot.status %></h6>
    </div>
  </div>
</div>

app/views/host/slots/index.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'>Organize your availabilities</h4>
  </div>
</div>

<div class='row'>
  <div class='col-xl-4 col-12'>
    <%= form_with model: [:host, Slot.new], local: true do |form| %>
      <div class='card' id='slot-card-new'>
        <div class='card-body'>
          <h5 class='card-title'>New availability :</h5>
          <h6 class='card-subtitle'><%= form.date_field :scheduled_at %> for <%= form.select :daytime, Slot.daytimes.keys.to_a %></h5>
          <h6 class='card-subtitle'>Max number of people : <%= form.select :max_people, (1..10).map { |int| [int, int]} %></h6>
          <%= form.submit 'Create slot' %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render @slots %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hastati Alpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class='row'>
      <div class='col-12'>
        <%= render partial: 'navbar' %>
      </div>
    </div>

    <section class='container-fluid'>
      <div class='row'>
        <div class='col'>
          <%= render partial: 'flash' %>
        </div>
      </div>

      <div class='main-page-container'>
          <%= yield %>
      </div>

    </section>


    <footer>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </footer>

  </body>
</html>

app/views/profiles/edit.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'>Account informations</h4>
  </div>
</div>

<%= form_with model: @profile, local: true do |form| %>
  <div class='row'>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :firstname %>
        <%= form.text_field :firstname, value: @profile.firstname, class: 'form-control' %>
      </div>
    </div>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :lastname %>
        <%= form.text_field :lastname, value: @profile.lastname, class: 'form-control' %>
      </div>
    </div>
  </div>
  <br>
  <div class='row'>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :street %>
        <%= form.text_field :street, value: @profile.street, class: 'form-control' %>
      </div>
    </div>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :zipcode %>
        <%= form.text_field :zipcode, value: @profile.zipcode, class: 'form-control' %>
      </div>
    </div>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :city %>
        <%= form.text_field :city, value: @profile.city, class: 'form-control' %>
      </div>
    </div>
    <div class='col-xl-6'>
      <div class='form-group'>
        <%= form.label :country %>
        <%= form.text_field :country, value: @profile.country, class: 'form-control' %>
      </div>
    </div>
  </div>
  <br>
  <div class='row'>
    <div class='col-xl-12'>
        <%= form.submit 'Save informations', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class='row'>
  <div class='col-xl-12'>
    <h4 class='page-title-header'>Account informations</h4>
  </div>
</div>

<div class='row'>
  <div class='col-xl-12'>
    <p>Email : <%= current_user.email %></p>
    <p>Full name : <%= @profile.fullname %></p>
    <p>Address : <%= @profile.address %></p>
    <%= link_to 'Edit my informations', edit_profile_path %>
  </div>
</div>

app/views/slots/index.html.erb
<h1>Slots for <%= current_user.email %> : <%= @slots.count %></h1>
<hr>

<%= form_with model: Slot.new, local: true do |form| %>
  <%= form.label :date_field, 'Slot date :' %>
  <%= form.date_field :scheduled_at %>
  <%= form.label :daytime, 'Slot period :' %>
  <%= form.select :daytime, Slot.daytimes.keys.to_a %>
  <%= form.label :max_people, 'Max number of people :' %>
  <%= form.select :max_people, (1..10).map { |int| [int, int]} %>
  <%= form.submit 'Create slot' %>
<% end %>
<hr>

<ul>
  <%= render @slots %>
</ul>